name: Spellcheck

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  spellcheck:
    name: Spelling
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        show-progress: false
    - uses: codespell-project/actions-codespell@master
      with:
        builtin: clear,en-GB_to_en-US
        path: _posts, 
